export const FETCH_SALES = 'FETCH_SALES';
export const FETCH_SALES_SUCCESS = 'FETCH_SALES_SUCCESS';
export const FETCH_SALES_ERROR = 'FETCH_SALES_ERROR';

export const ENABLE_SALES_LOADER = 'ENABLE_SALES_LOADER';
export const ENABLE_DUPLICATES_LOADER = 'ENABLE_DUPLICATES_LOADER';

export const FETCH_DEADLINES = 'FETCH_DEADLINES';
export const FETCH_DEADLINES_SUCCESS = 'FETCH_DEADLINES_SUCCESS';
export const FETCH_DEADLINES_ERROR = 'FETCH_DEADLINES_ERROR';

export const FETCH_DUPLICATES = 'FETCH_DUPLICATES';
export const FETCH_DUPLICATES_SUCCESS = 'FETCH_DUPLICATES_SUCCESS';
export const FETCH_DUPLICATES_ERROR = 'FETCH_DUPLICATES_ERROR';

export const MERGE_DUPLICATES = 'MERGE_DUPLICATES';
export const MERGE_DUPLICATES_SUCCESS = 'MERGE_DUPLICATES_SUCCESS';
export const MERGE_DUPLICATES_ERROR = 'MERGE_DUPLICATES_ERROR';