export const FETCH_SALES = 'FETCH_SALES';
export const FETCH_SALES_SUCCESS = 'FETCH_SALES_SUCCESS';
export const FETCH_SALES_ERROR = 'FETCH_SALES_ERROR';

export const ENABLE_SALES_LOADER = 'ENABLE_SALES_LOADER';

export const FETCH_DEADLINES = 'FETCH_DEADLINES';
export const FETCH_DEADLINES_SUCCESS = 'FETCH_DEADLINES_SUCCESS';
export const FETCH_DEADLINES_ERROR = 'FETCH_DEADLINES_ERROR';